config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :restaurants, only: [:index, :new, :create, :show] do
    resources :reviews, only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  # has_many :reviews, dependent: :destroy
  has_many :reviews, dependent: :destroy

  validates :name, :address, :category, presence: true

  CATEGORY = ["chinese", "italian", "japanese", "french", "belgian"]
  validates :category, inclusion: { in: CATEGORY }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :content, presence: true
  validates :restaurant, presence: true
  validates :rating, presence: true, inclusion: { in: [0, 1, 2, 3, 4, 5] }, numericality: { only_integer: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show]
  def index
    @restaurants = Restaurant.all
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.create(restaurant_params)
    if @restaurant.save
      redirect_to @restaurant, notice: 'Restaurant was successfully created.'
    else
      render :new
    end
  end

  def show
    @review = Review.new
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :category, :phone_number)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def new
    @review = Review.new
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def create
    @review = Review.new(review_params)
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review.restaurant = @restaurant

    if @review.save
      redirect_to @restaurant, notice: 'Restaurant was successfully created.'
    else
      render :new
    end
  end


  private

  def review_params
    params.require(:review).permit(:rating, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="conteiner">
    <div class="row justify-content-center">
      <div class="col-9">
        <%= yield %>
      </div>
    </div>
  </div>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= simple_form_for(restaurant) do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :phone_number %>
  <%= f.input :category, collection: Restaurant::CATEGORY %>
  <%= f.button :submit, class: 'btn btn-primary' %>
<% end %>

app/views/restaurants/index.html.erb
<h1>Restaurants</h1>

<ol>

    <% @restaurants.each do |restaurant| %>
     <li><%= link_to restaurant.name, restaurant_path(restaurant)%></li>
    <% end %>

</ol>

<%= link_to 'Add a new restaurant', new_restaurant_path, class: 'btn btn-primay'%>

app/views/restaurants/new.html.erb
<h2 class="d-flex justify-content-center">Add a new restaurant</h2>

<%= render 'form', restaurant: @restaurant %>
<%= link_to 'All restaurants', restaurants_path(@restaurant) %>

app/views/restaurants/show.html.erb
<h1 class="d-flex justify-content-center"><%= @restaurant.name %></h1>

<h2><strong>Address:</strong>
    <%= @restaurant.address %></h2>

<h3><strong>Category:</strong>
    <%= @restaurant.category %></h3>

<h4>Contact-Us: <%= @restaurant.phone_number %></h4>

<h4>The reviews</h4>

<ul>
<% @restaurant.reviews.each do |review| %>
  <li>
        <%= review.content %>
        <%= review.rating %>
  </li>
<% end %>
</ul>

<%= link_to 'Add a review', new_restaurant_review_path(@restaurant) %>
<%= link_to 'All Restaurants', restaurants_path(@restaurant) %>

app/views/reviews/_form.html.erb
<%= simple_form_for ([@restaurant, @review]) do |f| %>
  <%= f.input :content, placeholder: "Write something about this restaurant" %>
  <%= f.input :rating, placeholder: "How would you like to rate this restaurant(1-5)" %>
  <%= f.submit "Add a review", class: "btn btn-primary" %>
<% end %>

app/views/reviews/new.html.erb
<%= render "form", review: @review %>
<%= link_to 'Changed my mind', restaurants_path(@restaurant) %>